site_name: SWARH Apps Documentation

theme:
  name: material
  logo: assets/swarh.png

extra_css: 
  - stylesheets/extra.css

markdown_extensions:
  - markdown.extensions.fenced_code
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - sane_lists